#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase

# rm -rf processor*
# rm -rf log*
# rm -rf *.out 
# cp constant/polyMesh/blockMeshDict ./
# rm -rf constant/polyMesh/*
# mv ./blockMeshDict constant/polyMesh/blockMeshDict
