#!/bin/bash

# Number of nodes and cores to use
nodes=1
cores=4
# cores=8

# Make the mesh using blockMesh (serial)
blockMesh 2>&1 | tee log.blockMesh

# Decompose the mesh and solution files (serial)
decomposePar 2>&1 | tee log.decomposePar

# Run the solver (parallel)
# mpirun -np $(($nodes*$cores)) fastPisoSolver -parallel 2>&1 | tee log.fastPisoSolver
mpirun -np $(($nodes*$cores)) pisoFoamTurbine -parallel 2>&1 | tee log.pisoFoamTurbine

# Post-Processing
# reconstruct the parallel filess for all times, or for only specific times
reconstructPar
# reconstructPar -time '2,4'

# convert OpenFOAM format to VTK files
foamToVTK